# Generated by Cloud66 Starter
FROM ruby:2.6.5

# Install common dependencies
RUN apt-get update \
  && apt-get install -y build-essential nodejs curl net-tools \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install Yarn
RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- \
  && ln -sf $HOME/.yarn/bin/yarn /usr/local/bin/yarn \
  && ln -sf $HOME/.yarn/bin/yarnpkg /usr/local/bin/yarnpkg

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install

ADD . $APP_HOME
RUN yarn install && yarn upgrade
RUN rake assets:precompile