# Generated by Cloud66 Starter
FROM ruby:2.6.5

RUN apt-get update -qq && apt-get install -y build-essential nodejs curl
RUN curl -o- -L https://yarnpkg.com/install.sh | bash

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install

ADD . $APP_HOME
RUN /root/.yarn/bin/yarn upgrade
RUN rake assets:precompile
